### ISSUE TITLE
Formatting error with Figure 3

### ISSUE THREAD

**Issue by jonahweissman** [distillpub/post--differentiable-parameterizations#81]
In my browser, Figure 3 is overlapping the text below it:

![capture](https://user-images.githubusercontent.com/19804455/43228130-bd149d38-902e-11e8-9196-449983e75ddb.PNG)

I'm on Firefox 52.9.0 (32-bit). If you need more info, let me know.

**Comment by ludwigschubert** [comment]
Thanks @jonahweissman! This diagram is indeed using a new-ish scaling approach that we wanted to test before potentially deploying more widely—good to know that it immediately ran into cross-browser compatibility issues. 👎 
I'll test on your version of FF and fix or abandon this approach.
