### ISSUE TITLE
Caption of figure 18

### ISSUE THREAD

**Issue by kittentronic** [distillpub/post--differentiable-parameterizations#90]
The title of the source image used for the style transfer to the 3D printed rabbit shape is given as 'The large one parades on red bottom', as per the linked Wikiart page. However this is an egregiously bad (machine?) translation of the original title, _Le grand parade sur fond rouge_. Either use the artist's original title, or substitute a better translation e.g. _Grand parade with red background_ (from [here](http://www.ngv.vic.gov.au/explore/collection/work/67286/), a mosaic rendition of the Leger painting).

**Comment by ludwigschubert** [comment]
…I know, right? I remember being confused by the translated title but not finding the original—which seems to be right there on the WikiArt page, so not sure how that happened. Thanks for pointing it out, now we only need to let WikiArt know, too.

**Comment by ludwigschubert** [comment]
Changed to French title (_La grand parade sur fond rouge_). :-)

**Comment by ludwigschubert** [comment]
I've [updated the Wikiart title](https://www.wikiart.org/en/fernand-leger/the-large-one-parades-on-red-bottom-1953), too. I hope "Grand parade *on* red background" stays closest to the original title. :-)

**Comment by kittentronic** [comment]
Great, thanks for a fascinating article!
